apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-service-green
  template:
    metadata:
      labels:
        app: web-service-green
    spec:
      containers:
      - name: web-service
        image: frimeshani/frimeshani/web-service:latest
        ports:
        - containerPort: 3000